### ISSUE TITLE
Include NBN expected dates

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#135]
NBN has published the expected date for each previously announced suburb, incorporate this into the site.

**Comment by kiwisg124** [comment]
After adding suburb expected date, the processing schedule might give priority to new suburbs / regions now upgradable rather than each suburb on their assigned processing calendar day (if that is how you manage this).  Amend processing schedule so that suburbs with a future expected date are done after suburbs with a prior expected date which are experiencing high rates of upgrades now. Add a results summary metric to the suburb which counts results for this and remembers the same for the  prior run - easier to identify suburbs currently experiencing highest rates of change in upgrade options. By doing these first there is less chance of excess API calls being wasted for very few changes in premises upgrade options ? Analysis may show the expected uptake by suburb, after factoring in socio-economic conditions, and the current balance of HFC:NBN etc. Am interested in modelling that can predict take up. For example rates of mortgages in arrears are increasing in certain suburbs which must limit capacity to increase revenue per service. Visual checks suggest some suburbs not yet announced by NBN and yet with numerous FTTP connections. Consider how to expose the suburb processing date as a leading AS AT DD-MM value in the Technology count display. Awesome application. Thanks!

**Comment by LukePrior** [comment]
Yeah this is exactly the plan, unfortunately I'm occupied currently so won't have any time to work on it in the immediate future, but open to quality Pull Requests.

**Comment by lyricnz** [comment]
Maybe this issue should link to WHERE NBN has published this information

**Comment by lyricnz** [comment]
Assume that the URL above is accurate, here's a script to parse that page, and produce a JSON file containing state->suburb->date

```python
# parse a NBN web page to get a list of all suburb upgrade dates
import json
import re
import requests

from bs4 import BeautifulSoup

URL = 'https://www.nbnco.com.au/residential/upgrades/more-fibre'
content = requests.get(URL).content

results = {}

soup = BeautifulSoup(content, "html.parser")
for state_element in soup.find(id="accordion-c467de9e93").find_all("div", class_="cmp-accordion__item"):
    state = state_element.find("span", class_="cmp-accordion__title").text
    results[state] = {}
    for p in state_element.find("div", class_="cmp-text").find_all("p"):
        suburbs = re.findall(r'^(.*) - from (\w+ \d{4})', p.text, flags=re.MULTILINE)
        results[state].update({s[0]: s[1] for s in suburbs})
    print(state, len(results[state]), results[state])

with open("results/suburb-dates.json", "w") as outfile:
    json.dump(results, outfile, indent=4)
```

Results attached
[suburb-dates.json.txt](https://github.com/LukePrior/nbn-upgrade-map/files/11900768/suburb-dates.json.txt)

What do do with this?

**Comment by LukePrior** [comment]
> I found _a_ copy of this information in a popup that you can get from https://www.nbnco.com.au/residential/upgrades/more-fibre

That is also where I found it, not sure if it exists anywhere else publically.

> What do do with this?

I think the way suburbs are stored will need to be redesigned so additional information can be stored alongside them such as this. Instead of multiple files maybe a single master file containing every suburb with information such as whether it's been announced for upgrade, and the expected date for upgrade, along with date last updated.

Then instead of sequentially working through the list to select what suburb to update next an algorithm would need to be designed so that suburbs with ongoing works get updated more often.

**Comment by lyricnz** [comment]
Yup. Start by abstracting the behaviour away into a interface, then change how it works.

**Comment by lyricnz** [comment]
Interestingly there are many more suburbs in the date-list than in the announced-list.  Is including them in the date list an implicit announcement?

announced Counter({'NSW': 473, 'QLD': 387, 'VIC': 247, 'WA': 224, 'SA': 151, 'TAS': 31, 'ACT': 19, 'NT': 13, 'OT': 0})
dates Counter({'NSW': 831, 'QLD': 655, 'VIC': 455, 'WA': 345, 'SA': 250, 'TAS': 99, 'ACT': 53, 'NT': 13, 'OT': 0})

There's also a few states that have been announced but don't have dates in this latest list:

Announced Hume, ACT - but no date
Announced O'Connor, ACT - but no date
Announced Brighton-Le-Sands, NSW - but no date
Announced Coolangatta, NSW - but no date
Announced Liverpool, NSW - but no date
Announced Claymore, NSW - but no date
Announced Hastings Point, NSW - but no date
Announced Ilparpa, NT - but no date
Announced Bald Hills, QLD - but no date
Announced Ashgrove, QLD - but no date
Announced Kippa-Ring, QLD - but no date
Announced O'Halloran Hill, SA - but no date
Announced O'Connor, WA - but no date

**Comment by LukePrior** [comment]
Huh that is interesting, I think it makes sense to take them as an implicit announcement.

**Comment by lyricnz** [comment]
With a couple of names fixed (apostrophes) the current list of "announced previously, but no date in latest list" is

Announced Hume, ACT - but no date
Announced Hastings Point, NSW - but no date
Announced Liverpool, NSW - but no date
Announced Claymore, NSW - but no date
Announced Coolangatta, NSW - but no date
Announced Ilparpa, NT - but no date
Announced Ashgrove, QLD - but no date
Announced Bald Hills, QLD - but no date

**Comment by lyricnz** [comment]
I think this can be closed. There's a separate issue https://github.com/LukePrior/nbn-upgrade-map/issues/191 to add this information to the map.
