### ISSUE TITLE
Once total pass is complete?

### ISSUE THREAD

**Issue by Jorvanus** [LukePrior/nbn-upgrade-map#214]
What is the plan once total pass is complete?  Surely just loop through the announced sites on repeat given there won't be a change in any of the rest of the suburbs.

**Comment by kiwisg124** [comment]
After total pass is attained, the next run might examine suburbs in the following order ..
suburbs which are new in the latest NBN listing ( no processing date )
oldest processing date first to catch-up
suburbs which became orderable recently - announcement date between current date -31  and + 31 days 

In the latest update by NBN a number of announcement dates for July-2023 were brought forward to June-2023.

**Comment by lyricnz** [comment]
We are now at 100%

Once a couple of PRs are merged, it will start reprocessing announced suburbs, in order from the oldest-updated to new, around and around.  It should be a bit faster because it uses the previous results to cache the address->locid lookup.
 
https://github.com/LukePrior/nbn-upgrade-map/pull/221
https://github.com/LukePrior/nbn-upgrade-map/pull/219

**Comment by LukePrior** [comment]
The changes in recent PR will ensure that the program doesn't get stuck but additional logic will have to be introduced so suburbs that haven't been announced are ignored and suburbs with the nearest announcement date are checked most often

**Comment by lyricnz** [comment]
I think we can close this.
